### ISSUE TITLE
Question about models.SGF_model

### ISSUE THREAD

**Issue by SuooL** [LijunRio/A-Self-Guided-Framework#1]
At the step "To train the SGF", there was an error report:

```
Traceback (most recent call last):
  File "/path/A-Self-Guided-Framework/KMVE_RG/my_main.py", line 4, in <module>
    from models.SGF_model import SGF
ModuleNotFoundError: No module named 'models'
```

**Comment by LijunRio** [comment]
Thanks for your interest in our project. The mesh_label is the clustering result in the KD module. 
The annotations file' format is below here.
Due to we have some further projects based on these files with the hospital, I cannot give your these files now. We will release the files after these project done. You can download the original dataset and replace in the format above.


Thanks for your interest ！


| |
黎郡 2016113015
|
|
***@***.***
|
签名由网易邮箱大师定制
On 7/18/2022 ***@***.***> wrote：

I saw the updated codes, thank you very much for your prompt reply.

I am also confused about the annotation file in your codes, especially for the fields related to mesh_label, could you please upload your annotation.json file?

Thanks again for your help, looking forward to your reply!
